services:
  meeshbot:
    container_name: meeshbot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - meeshbot-network
    ports:
      - "8000:8000"
    volumes:
      - ./meeshbot:/code/meeshbot

  postgres:
    container_name: meeshbot-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: meeshbot
      POSTGRES_USER: meeshbot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - meeshbot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  meeshbot-network:
    name: meeshbot-network
    driver: bridge
