# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from datetime import date, datetime, time
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager

class GroupMeMessage(Model):
    class Meta:
        is_table: bool

    id: str
    group: GroupMeGroup
    sender: GroupMeUser | None
    text: str | None
    system: bool
    attachments: list[dict]
    timestamp: datetime
    group_id: str
    sender_id: str | None
    objects: "GroupMeMessageManager"

class GroupMeMessageQuery(Query[GroupMeMessage]):
    """Type-safe Query for GroupMeMessage model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        attachments: list[dict] | None = None,
        attachments__in: list[list[dict]] | None = None,
        attachments__isnull: bool | None = None,
        group: GroupMeGroup | None = None,
        group__in: list[GroupMeGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        sender: GroupMeUser | None = None,
        sender__in: list[GroupMeUser] | None = None,
        sender__isnull: bool | None = None,
        sender_id: str | None = None,
        sender_id__contains: str | None = None,
        sender_id__icontains: str | None = None,
        sender_id__startswith: str | None = None,
        sender_id__istartswith: str | None = None,
        sender_id__endswith: str | None = None,
        sender_id__iendswith: str | None = None,
        sender_id__iexact: str | None = None,
        sender_id__in: list[str] | None = None,
        sender_id__isnull: bool | None = None,
        system: bool | None = None,
        system__in: list[bool] | None = None,
        system__isnull: bool | None = None,
        text: str | None = None,
        text__contains: str | None = None,
        text__icontains: str | None = None,
        text__startswith: str | None = None,
        text__istartswith: str | None = None,
        text__endswith: str | None = None,
        text__iendswith: str | None = None,
        text__iexact: str | None = None,
        text__in: list[str] | None = None,
        text__isnull: bool | None = None,
        timestamp: datetime | None = None,
        timestamp__gt: datetime | None = None,
        timestamp__gte: datetime | None = None,
        timestamp__lt: datetime | None = None,
        timestamp__lte: datetime | None = None,
        timestamp__between: tuple[datetime, datetime] | None = None,
        timestamp__range: datetime | None = None,
        timestamp__year: int | None = None,
        timestamp__month: int | None = None,
        timestamp__day: int | None = None,
        timestamp__in: list[datetime] | None = None,
        timestamp__isnull: bool | None = None,
    ) -> "GroupMeMessageQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        attachments: list[dict] | None = None,
        attachments__in: list[list[dict]] | None = None,
        attachments__isnull: bool | None = None,
        group: GroupMeGroup | None = None,
        group__in: list[GroupMeGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        sender: GroupMeUser | None = None,
        sender__in: list[GroupMeUser] | None = None,
        sender__isnull: bool | None = None,
        sender_id: str | None = None,
        sender_id__contains: str | None = None,
        sender_id__icontains: str | None = None,
        sender_id__startswith: str | None = None,
        sender_id__istartswith: str | None = None,
        sender_id__endswith: str | None = None,
        sender_id__iendswith: str | None = None,
        sender_id__iexact: str | None = None,
        sender_id__in: list[str] | None = None,
        sender_id__isnull: bool | None = None,
        system: bool | None = None,
        system__in: list[bool] | None = None,
        system__isnull: bool | None = None,
        text: str | None = None,
        text__contains: str | None = None,
        text__icontains: str | None = None,
        text__startswith: str | None = None,
        text__istartswith: str | None = None,
        text__endswith: str | None = None,
        text__iendswith: str | None = None,
        text__iexact: str | None = None,
        text__in: list[str] | None = None,
        text__isnull: bool | None = None,
        timestamp: datetime | None = None,
        timestamp__gt: datetime | None = None,
        timestamp__gte: datetime | None = None,
        timestamp__lt: datetime | None = None,
        timestamp__lte: datetime | None = None,
        timestamp__between: tuple[datetime, datetime] | None = None,
        timestamp__range: datetime | None = None,
        timestamp__year: int | None = None,
        timestamp__month: int | None = None,
        timestamp__day: int | None = None,
        timestamp__in: list[datetime] | None = None,
        timestamp__isnull: bool | None = None,
    ) -> "GroupMeMessageQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(
        self,
        *fields: Literal[
            "attachments",
            "-attachments",
            "group",
            "-group",
            "group_id",
            "-group_id",
            "id",
            "-id",
            "sender",
            "-sender",
            "sender_id",
            "-sender_id",
            "system",
            "-system",
            "text",
            "-text",
            "timestamp",
            "-timestamp",
        ],
    ) -> "GroupMeMessageQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "GroupMeMessageQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "GroupMeMessageQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "GroupMeMessageQuery":
        """Return distinct results."""
        ...

    def select(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
    ) -> "GroupMeMessageQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "GroupMeMessageQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "GroupMeMessageQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "GroupMeMessageQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "GroupMeMessageQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "GroupMeMessageQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
    ) -> "GroupMeMessageQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "GroupMeMessageQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
    ) -> "GroupMeMessageQuery":
        """Return dicts instead of models."""
        ...

    def values_list(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
        flat: bool = False,
    ) -> "GroupMeMessageQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[GroupMeMessage]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeMessage | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeMessage | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class GroupMeMessageManager(QueryManager[GroupMeMessage]):
    """Type-safe Manager for GroupMeMessage model."""

    # Query building methods (sync, return Query)

    def query(self) -> GroupMeMessageQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        attachments: list[dict] | None = None,
        attachments__in: list[list[dict]] | None = None,
        attachments__isnull: bool | None = None,
        group: GroupMeGroup | None = None,
        group__in: list[GroupMeGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        sender: GroupMeUser | None = None,
        sender__in: list[GroupMeUser] | None = None,
        sender__isnull: bool | None = None,
        sender_id: str | None = None,
        sender_id__contains: str | None = None,
        sender_id__icontains: str | None = None,
        sender_id__startswith: str | None = None,
        sender_id__istartswith: str | None = None,
        sender_id__endswith: str | None = None,
        sender_id__iendswith: str | None = None,
        sender_id__iexact: str | None = None,
        sender_id__in: list[str] | None = None,
        sender_id__isnull: bool | None = None,
        system: bool | None = None,
        system__in: list[bool] | None = None,
        system__isnull: bool | None = None,
        text: str | None = None,
        text__contains: str | None = None,
        text__icontains: str | None = None,
        text__startswith: str | None = None,
        text__istartswith: str | None = None,
        text__endswith: str | None = None,
        text__iendswith: str | None = None,
        text__iexact: str | None = None,
        text__in: list[str] | None = None,
        text__isnull: bool | None = None,
        timestamp: datetime | None = None,
        timestamp__gt: datetime | None = None,
        timestamp__gte: datetime | None = None,
        timestamp__lt: datetime | None = None,
        timestamp__lte: datetime | None = None,
        timestamp__between: tuple[datetime, datetime] | None = None,
        timestamp__range: datetime | None = None,
        timestamp__year: int | None = None,
        timestamp__month: int | None = None,
        timestamp__day: int | None = None,
        timestamp__in: list[datetime] | None = None,
        timestamp__isnull: bool | None = None,
    ) -> GroupMeMessageQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        attachments: list[dict] | None = None,
        attachments__in: list[list[dict]] | None = None,
        attachments__isnull: bool | None = None,
        group: GroupMeGroup | None = None,
        group__in: list[GroupMeGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        sender: GroupMeUser | None = None,
        sender__in: list[GroupMeUser] | None = None,
        sender__isnull: bool | None = None,
        sender_id: str | None = None,
        sender_id__contains: str | None = None,
        sender_id__icontains: str | None = None,
        sender_id__startswith: str | None = None,
        sender_id__istartswith: str | None = None,
        sender_id__endswith: str | None = None,
        sender_id__iendswith: str | None = None,
        sender_id__iexact: str | None = None,
        sender_id__in: list[str] | None = None,
        sender_id__isnull: bool | None = None,
        system: bool | None = None,
        system__in: list[bool] | None = None,
        system__isnull: bool | None = None,
        text: str | None = None,
        text__contains: str | None = None,
        text__icontains: str | None = None,
        text__startswith: str | None = None,
        text__istartswith: str | None = None,
        text__endswith: str | None = None,
        text__iendswith: str | None = None,
        text__iexact: str | None = None,
        text__in: list[str] | None = None,
        text__isnull: bool | None = None,
        timestamp: datetime | None = None,
        timestamp__gt: datetime | None = None,
        timestamp__gte: datetime | None = None,
        timestamp__lt: datetime | None = None,
        timestamp__lte: datetime | None = None,
        timestamp__between: tuple[datetime, datetime] | None = None,
        timestamp__range: datetime | None = None,
        timestamp__year: int | None = None,
        timestamp__month: int | None = None,
        timestamp__day: int | None = None,
        timestamp__in: list[datetime] | None = None,
        timestamp__isnull: bool | None = None,
    ) -> GroupMeMessageQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
    ) -> GroupMeMessageQuery:
        """Return dicts instead of models."""
        ...

    def values_list(
        self,
        *fields: Literal[
            "attachments",
            "group",
            "group_id",
            "id",
            "sender",
            "sender_id",
            "system",
            "text",
            "timestamp",
        ],
        flat: bool = False,
    ) -> GroupMeMessageQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> GroupMeMessageQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> GroupMeMessageQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> GroupMeMessageQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> GroupMeMessageQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> GroupMeMessageQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> GroupMeMessage:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> GroupMeMessage | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[GroupMeMessage, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[GroupMeMessage]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeMessage | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeMessage | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: GroupMeMessage | None = None,
        client: Any | None = None,
        using: str | None = None,
        attachments: list[dict] | None = None,
        group: GroupMeGroup | None = None,
        group_id: str | None = None,
        id: str | None = None,
        sender: GroupMeUser | None = None,
        sender_id: str | None = None,
        system: bool | None = None,
        text: str | None = None,
        timestamp: datetime | None = None,
    ) -> GroupMeMessage:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[GroupMeMessage],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[GroupMeMessage]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[GroupMeMessage],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
