# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager


class GroupMeUser(Model):
    class Meta:
        is_table: bool
    id: str
    name: str
    image_url: str | None
    muted: bool
    objects: "GroupMeUserManager"


class GroupMeUserQuery(Query[GroupMeUser]):
    """Type-safe Query for GroupMeUser model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        image_url: str | None = None,
        image_url__contains: str | None = None,
        image_url__icontains: str | None = None,
        image_url__startswith: str | None = None,
        image_url__istartswith: str | None = None,
        image_url__endswith: str | None = None,
        image_url__iendswith: str | None = None,
        image_url__iexact: str | None = None,
        image_url__in: list[str] | None = None,
        image_url__isnull: bool | None = None,
        muted: bool | None = None,
        muted__in: list[bool] | None = None,
        muted__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> "GroupMeUserQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        image_url: str | None = None,
        image_url__contains: str | None = None,
        image_url__icontains: str | None = None,
        image_url__startswith: str | None = None,
        image_url__istartswith: str | None = None,
        image_url__endswith: str | None = None,
        image_url__iendswith: str | None = None,
        image_url__iexact: str | None = None,
        image_url__in: list[str] | None = None,
        image_url__isnull: bool | None = None,
        muted: bool | None = None,
        muted__in: list[bool] | None = None,
        muted__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> "GroupMeUserQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "image_url", "-image_url", "muted", "-muted", "name", "-name"]) -> "GroupMeUserQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "GroupMeUserQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "GroupMeUserQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "GroupMeUserQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "image_url", "muted", "name"]) -> "GroupMeUserQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "GroupMeUserQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "GroupMeUserQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "GroupMeUserQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "GroupMeUserQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "GroupMeUserQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "image_url", "muted", "name"]) -> "GroupMeUserQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "GroupMeUserQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "image_url", "muted", "name"]) -> "GroupMeUserQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "image_url", "muted", "name"], flat: bool = False) -> "GroupMeUserQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[GroupMeUser]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeUser | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeUser | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class GroupMeUserManager(QueryManager[GroupMeUser]):
    """Type-safe Manager for GroupMeUser model."""

    # Query building methods (sync, return Query)

    def query(self) -> GroupMeUserQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        image_url: str | None = None,
        image_url__contains: str | None = None,
        image_url__icontains: str | None = None,
        image_url__startswith: str | None = None,
        image_url__istartswith: str | None = None,
        image_url__endswith: str | None = None,
        image_url__iendswith: str | None = None,
        image_url__iexact: str | None = None,
        image_url__in: list[str] | None = None,
        image_url__isnull: bool | None = None,
        muted: bool | None = None,
        muted__in: list[bool] | None = None,
        muted__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> GroupMeUserQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        image_url: str | None = None,
        image_url__contains: str | None = None,
        image_url__icontains: str | None = None,
        image_url__startswith: str | None = None,
        image_url__istartswith: str | None = None,
        image_url__endswith: str | None = None,
        image_url__iendswith: str | None = None,
        image_url__iexact: str | None = None,
        image_url__in: list[str] | None = None,
        image_url__isnull: bool | None = None,
        muted: bool | None = None,
        muted__in: list[bool] | None = None,
        muted__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> GroupMeUserQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "image_url", "muted", "name"]) -> GroupMeUserQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "image_url", "muted", "name"], flat: bool = False) -> GroupMeUserQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> GroupMeUserQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> GroupMeUserQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> GroupMeUserQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> GroupMeUserQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> GroupMeUserQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> GroupMeUser:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> GroupMeUser | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[GroupMeUser, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[GroupMeUser]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeUser | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> GroupMeUser | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: GroupMeUser | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: str | None = None,
        image_url: str | None = None,
        muted: bool | None = None,
        name: str | None = None,
    ) -> GroupMeUser:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[GroupMeUser],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[GroupMeUser]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[GroupMeUser],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
